### ISSUE TITLE
Script cannot locate "$filename"

### ISSUE THREAD

**Issue by skidunion** [dentys03/manual_duplex_linux#2]
The duplexer script gets stuck here, because it can't find the job file.
https://github.com/dentys03/manual_duplex_linux/blob/9e98dab125f92e3cc8612a84501d1c23ac7e0668/usr/lib/cups/backend/duplex-print#L48-L52

Here's what the folder looks like when I send the job:
```
Permissions Size User Group Date Modified Name
drwx--x---     - root lp    31 Oct 23:43  /var/spool/cups
.rw-------  1.4k root lp    31 Oct 23:37  ├── c00062
.rw-------  1.4k root lp    31 Oct 23:37  ├── c00063
.rw-------  1.4k root lp    31 Oct 23:39  ├── c00064
.rw-------  1.4k root lp    31 Oct 23:40  ├── c00065
.rw-------  1.4k root lp    31 Oct 23:40  ├── c00066
.rw-r-----  833k root lp    31 Oct 23:35  ├── d00062-001
.rw-r-----  1.3M root lp    31 Oct 23:37  ├── d00063-001
.rw-r-----  833k root lp    31 Oct 23:38  ├── d00064-001
.rw-r-----  833k root lp    31 Oct 23:39  ├── d00065-001
.rw-r-----  833k root lp    31 Oct 23:40  ├── d00066-001
.rw-r-----  833k root lp    31 Oct 23:43  ├── d00067-001
drwxrwxrwx     - root root  31 Oct 23:31  ├── duplex
drwxrwx--T     - root lp    31 Oct 23:43  └── tmp
.rw-------     0 lp   lp    31 Oct 23:32     └── cups-dbus-notifier-lockfile
```

And here's the print queue:

![image](https://user-images.githubusercontent.com/34306421/199108507-9675c586-48fc-4fd7-8327-bd6f93d056a4.png)

Also, I thought it would be odd that it's reporting the manufacturer's driver in the print dialog:

![image](https://user-images.githubusercontent.com/34306421/199108353-c0d74966-7a37-4bfc-af89-9f0e57187850.png)

**Comment by dentys03** [comment]
Hi.
Sorry for the late reply.

This script assumes /var/spool/cups/ is the folder used by the printing system.

Are you sure that's where the script is stuck? try to insert this in the loop
LOG $(date) --- Stuck waiting for file.

then test if /var/log/cups/error_log is full with those messages.

**Comment by skidunion** [comment]
I've tried to set up the script again, looks like this issue is resolved. I've successfully printed 'odd' pages. 

However, the user interface is not appearing.

```
Sat Jun 3 10:30:46 AM MSK 2023 --- Starting duplexer job
Sat Jun 3 10:30:46 AM MSK 2023 --- Script called by skidunion
Sat Jun 3 10:30:46 AM MSK 2023 --- Running on display number
Sat Jun 3 10:30:46 AM MSK 2023 --- page count: 2
Sat Jun 3 10:30:46 AM MSK 2023 --- more than one page was sent. printing odd pages
Sat Jun 3 10:30:46 AM MSK 2023 --- Will Show user interface.

(zenity:101950): Gtk-WARNING **: 10:30:46.210: cannot open display: 
Sat Jun 3 10:30:46 AM MSK 2023 --- User interface has been shown.
Sat Jun 3 10:30:46 AM MSK 2023 --- User aborted print job
```

**Comment by dentys03** [comment]
Hi.
Thanks for the feedback.
I think the smart solution would be to hardcode the width of the "proceed"  window to 300 and to let zenity choose the display. That should solve the issue or place it in zenity's backyard.

What's your opinion?

**Comment by skidunion** [comment]
Should be good.

That width calculation messes up the window for me anyway, so it would be better if you'd hardcode it.

**Comment by dentys03** [comment]
I found out that `who` and `w` are 2 different programs. Sorry. On my system was working by mistake.
I've updated the code.

zenity won't work if we don't export the display.
In what way is that calculation messing your window? can you post screenshot? 
Let's fix this too. Is better to size the window based on the resolution than to hardcode it.

**Comment by skidunion** [comment]
> In what way is that calculation messing your window? can you post screenshot?

![Screenshot_20230604_215651](https://github.com/dentys03/manual_duplex_linux/assets/34306421/fd3650b1-db12-43b0-95df-80945357c048)

Nevermind. The last time I tried it the "then press Proceed" text was really off to the right, now it's good for some reason

**Comment by dentys03** [comment]
I understand everything works now.
I'm closing this issue. I'm assuming it gets reopened automatically if you respond. Enjoy printing.
