### ISSUE TITLE
Extra blank page when printing only one (2-sided)

### ISSUE THREAD

**Issue by isidroas** [dentys03/manual_duplex_linux#9]
When a I ran the following command,
```
lp -P 43-44  book.pdf -d Manual_Duplexer_HP-LaserJet-Professional-P1102
```
an extra blank page is printed at the end.

**OS**: Ubuntu 23.10

**Comment by dentys03** [comment]
i think You've discovered this bug, which is noted in the README:
https://bugs.launchpad.net/ubuntu/+source/cups-filters/+bug/1340435

I haven't found a way around it.
